### ISSUE TITLE
Custom ENV variables

### ISSUE THREAD

**Issue by rafiki270** [vapor-community/Imperial#27]
It would be amazing if we could specify our own ENV variables so they can be defined in a uniform way in our application

**Comment by calebkleveter** [comment]
That sounds like a great idea! I have some plans to refactor a few things in Imperial for a 1.0 release, but I'm kind of tied up right now between work and ConsoleKit 4, so it will have to wait if I'm the one to do it 🙁. I'll be sure to add this though!

**Comment by rafiki270** [comment]
addressed in https://github.com/vapor-community/Imperial/pull/29
