### ISSUE TITLE
Create the Sign In With Apple provider :)

### ISSUE THREAD

**Issue by grosch** [vapor-community/Imperial#41]
Pretty please.

**Comment by calebkleveter** [comment]
I definitely want to do this soon. I can't guarantee when it will be done with my schedule, but I'll do it as soon as I get a chance.

**Comment by grosch** [comment]
Hi @calebkleveter.  Just wanted to give a small poke on this so you don't forget ;)

**Comment by grosch** [comment]
Really good info here about the server side part of this:

https://blog.curtisherbert.com/so-theyve-signed-in-with-apple-now-what/

**Comment by 0xTim** [comment]
So picking this up as I've implemented in a couple of client projects here - what do you want from Imperial for this? For doing it on iOS devices Imperial is not the way to do it since it's basically just a JWT

**Comment by grosch** [comment]
Nada.  I posted this way back when because you had originally told me to use Imperial when I was first asking you about this at WWDC, @0xTim

**Comment by 0xTim** [comment]
😅 well I'm going to reopen it because there's definitely scope to add SIWA as a provider to Imperial, it just needs to be made clear that it's for web (and android) only, iOS should just use JWT

**Comment by Strobocop** [comment]
Here's another good source of info that may ultimately be useful when implementing this: https://sarunw.com/posts/sign-in-with-apple-3/

**Comment by grosch** [comment]
Hey @calebkleveter, any ETA on this one?

**Comment by calebkleveter** [comment]
I'm so sorry. 😢 I really want to implement this but time constraints are not helping. I haven't done any work on this at all.

**Comment by 0xTim** [comment]
I've been looking at this and it doesn't really fit with Imperial right now. To start with, Apple's OAuth flow is non-existent until they decide to open it up. Secondly there's no real OAuth flow as Imperial understands it. You use the JS button which eventually calls a route on your app with the data. This provides a JWT token which you can use Vapor's JWT library to verify in a single line and there's not much else to do. There's a good write up on RW, [here's the relevant part](https://www.raywenderlich.com/11436647-sign-in-with-apple-using-vapor-4#toc-anchor-017). That's basically what Imperial would need to provide and most of it is vey app specific and would be delegated to Imperial's completion handler. I'm going to close this for now
