### ISSUE TITLE
How to access JWT scopes?

### ISSUE THREAD

**Issue by xavierLowmiller** [vapor-community/Imperial#49]
I'm trying to use Imperial for Google Login with my app.

Is there any guide on how to obtain the mail address that is part of Google's JWT?

I can see that the token is sent as part of Google's payload, but is discarded as only the access token is stored in the session.

Is there a best practice on how to obtain the mail address?

**Comment by 0xTim** [comment]
[This is how](https://github.com/raywenderlich/vapor-til/blob/master/Sources/App/Controllers/ImperialController.swift#L97) I get the user's email when signing in with Google

**Comment by xavierLowmiller** [comment]
Thanks! This helps me a lot!
