### ISSUE TITLE
We need working example for Imperial

### ISSUE THREAD

**Issue by e5faf2** [vapor-community/Imperial#6]
Could you please add working example for Imperial library? I'm not feel good with Usage Guide, especially for Google sign in.
It will be very helpful for newbies, like me.

**Comment by calebkleveter** [comment]
Yes, I can do that! Sorry I haven’t updated it yet. Just note that the current version is only compatible with Vapor 3, so you will have to use an older version if you are on version 2.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by calebkleveter** [comment]
Sorry it took me so long to get this fixed :blush:. I found some bugs with that occured when I updated Vapor 3 to the latest RC, so I got those fixed also. Docs should be up to date now!
