### ISSUE TITLE
Vapor 4 update

### ISSUE THREAD

**Issue by piers12** [vapor-community/Imperial#72]
Potentially starting a new project in the not too distant future that will need to use Shopify. Hoping to use Vapor and would be great to be able to use this package with Vapor 4.

**Comment by piers12** [comment]
Looks like circle ci is falling for your linked PR @0xTim (thanks for getting this sorted)

**Comment by 0xTim** [comment]
Yeah I've disabled CircleCI now we're on GH Actions
