### ISSUE TITLE
Auth0 support missing

### ISSUE THREAD

**Issue by paulyhedral** [vapor-community/Imperial#82]
The documentation mentions being able to use Auth0, but there doesn't seem to be any support for it in the code. The docs mention a package called `ImperialAuth-`, which doesn't exist, and (assuming that that is a type and the '-' is actually meant to be a '0'), attempting to import `ImperialAuth0` also fails.

**Comment by 0xTim** [comment]
Looks like it got missed off between the Vapor 4 release and being merged into the Vapor 3 branch. It should be simple enough to add if anyone wants to take this on

**Comment by jinthagerman** [comment]
Ive migrated this over to be compatible with the Vapor 4 release https://github.com/vapor-community/Imperial/pull/93
