### ISSUE TITLE
Maybe it is possible to update Imperial to async/await?

### ISSUE THREAD

**Issue by mynona** [vapor-community/Imperial#88]
As Vapor has been moved to async/await it would be great to have this updated as well.

**Comment by 0xTim** [comment]
Yep it should probably be done at some point but will likely need someone to step up and do it

**Comment by wibed** [comment]
i would like to take over and push this.

**Comment by chibombo** [comment]
@wibed:
All the help is welcome. Feel free to continue working on this. Create a PR and we can review it and merge it then.
